sensors: 
 - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
   point_cloud_topic: /kinect_head/depth_registered/points
   max_range: 5.0
   frame_subsample: 1
   point_subsample: 1
   padding_scale: 2.0
   padding_offset: 0.03


#sensors: 
# - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
#   point_cloud_topic: /tilt_cloud
#   max_range: 15.0
#   frame_subsample: 1
#   point_subsample: 1
#   padding_scale: 2.0
#   padding_offset: 0.03
#   filtered_cloud_topic: tilt_scan_self_filtered_cloud



